name: Build Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Using a stable, recent version is often best for CI
          # If you must use 3.13, you can specify '3.13'
          python-version: '3.12'

      - name: Install dependencies from frozen requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller on Windows
        if: runner.os == 'Windows'
        run: |
          pyinstaller run.py --name "NiTanPreapproval" --onefile --windowed `
          --icon=resources\icon-windows.ico `
          --add-data "config.yaml;." `
          --add-data "prompt_template.md;."

      - name: Build with PyInstaller on macOS (with UPX)
        if: runner.os == 'macOS'
        run: |
          pyinstaller --name "NiTanPreapproval" \
            --windowed \
            --icon resources/icon-mac.icns \
            --add-data "config.yaml:." \
            --add-data "prompt_template.md:." \
            run.py

      - name: Prepare artifact directory
        shell: bash
        run: |
          # 1. 创建最终的文件夹
          mkdir NiTanPreapproval
          
          # 2. 将构建好的应用移动到新文件夹中
          #    在 Windows 上, mv dist/NiTanPreapproval.exe NiTanPreapproval/
          #    在 macOS 上, mv dist/NiTanPreapproval.app NiTanPreapproval/
          #    使用通配符 * 可以同时兼容两种平台
          mv dist/NiTanPreapproval* NiTanPreapproval/
          
          # 3. 将配置文件也复制到新文件夹中
          cp config.yaml NiTanPreapproval/
          
          # 4. (可选) 打印出最终文件夹的内容, 方便调试
          echo "Final contents of the artifact directory:"
          ls -la NiTanPreapproval/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          # 上传的 zip 文件名
          name: NiTanPreapproval-${{ runner.os }}
          # 需要打包上传的文件夹路径
          path: NiTanPreapproval/